//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovoi.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        public int Id_расписания { get; set; }
        public int Id_группы { get; set; }
        public int Id_преподавателя { get; set; }
        public int Id_предмета { get; set; }
        public Nullable<System.TimeSpan> Время_занятий { get; set; }
        public System.DateTime День { get; set; }
        public Nullable<int> Id_кабинета { get; set; }
    
        public virtual Группа Группа { get; set; }
        public virtual Кабинет Кабинет { get; set; }
        public virtual Предмет Предмет { get; set; }
        public virtual Преподаватель Преподаватель { get; set; }
    }
}
