//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovoi.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        public int Id_студента { get; set; }
        public string Имя { get; set; }
        public int Id_курса { get; set; }
        public int id_группы { get; set; }
    
        public virtual Группа Группа { get; set; }
        public virtual Курс Курс { get; set; }
    }
}
